name: jaded
version: 0.1.1
author: Demis Bellot<demis.bellot@gmail.com>
description: Port of node.js popular Jade view engine for Dart.
homepage: https://github.com/dartist/jaded
documentation: https://github.com/visionmedia/jade/blob/master/Readme.md#readme-contents
dependencies:
  character_parser: any

#readme-contents
#readme-contents
#readme-contents
#dependencies:
#  unittest: any